---
- name: variables in ansible
  hosts: mongodb
  #this is play level variables, map
  vars:
   COURSE: DevOps with AWS
   TRAINER: Siva Reddy Medam
   DURATION: 120 HRS
  tasks:
   - name: print hello world
     ansible.builtin.debug:
      msg: "Hello, I am practicing DevOps"
   - name: print variables
     ansible.builtin.debug:
      msg: "Hello, I am practicing {{COURSE}},Trainer is {{TRAINER}},Duration is {{DURATION}}"
...