---
- name: variables to call from another playbook
  hosts: mongodb
  vars_files:
   - variables.yaml
  tasks:
   - name: print the variables
     ansible.builtin.debug:
      msg: "Hello I am practicing: {{COURSE}},Trainer is:{{TRAINER}},Duration is:{{DURATION}}"
...