- name: ansible variable data types
  hosts: mongodb
  vars:
   - AGE: 30 #Number
   - NAME: "Siva" #String
   - isDevOps: true #Boolean
   - Skills: #List
      - DevOps
      - AWS
      - Docker
     EXPERIENCE: #Map
      DevOps: 7
      AWS: 5
      Docker: 4
  tasks:
   - name: print number variable
     ansible.builtin.debug:
      msg: "{{AGE}}"
   - name: print string variable
     ansible.builtin.debug:
      msg: "{{NAME}}"
   - name: print boolean variable
     ansible.builtin.debug:
      msg: "{{isDevOps}}"
   - name: print list variable
     ansible.builtin.debug:
      msg: "{{Skills}}"
   - name: print map variables
     ansible.builtin.debug:
      msg: "{{EXPERIENCE}}"