---
- name: create user
  hosts: mongodb
  tasks:
   - name: check roboshop user exist or not 
     ansible.builtin.command: id roboshop
     register: output #output is variable name
     ignore_errors: true
   - name: print the command output
     ansible.builtin.debug:
      msg: "output is:{{output}}"
   - name: print the exit status
     ansible.builtin.debug:
      msg: "{{output.rc}}"
   - name: create user roboshop
     ansible.builtin.user:
     become: yes
      name: id roboshop
     when: output.rc =! 0
...