- name: Implementing loops 
  hosts: mongodb
  become: yes
  tasks:
   - name: Install packages using loops
     ansible.builtin.yum:
      name: "{{item}}"
      state: installed
     loop:
      - nginx
      - postfix
      - cyrus-sasl-plain
      - mailx