---
- name: Implementing advanced loops
  hosts: mongodb
  tasks:
   - name: Un-install packages
     ansible.builtin.yum: 
      name: "{{item.name}}"
      state: "{{item.state}}"
      #this is map
     with_items:
      - {name: nginx, state: absent}
      - {name: postfix,state: absent}
      - {name: 'cyrus-sasl-plain',state: 'absent'}
      - {name: 'mailx',state: absent}
...